#maven plugin help mojo generation informations
#Thu Jun 12 15:16:44 EDT 2025
destinationDirectory=/Users/pyjiang/repositories/finemop-tmp/emop/emop-maven-plugin/target/generated-sources/plugin
helpPackageName=edu.cornell
